workflows: 
  ios-workflow:
    name: iOS Flappy Bird
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: stable
      flutter: $FLUTTER_VERSION
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa